# version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  mongo:
    image: mongo
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  command:
    build:
      context: ./command
    ports:
      - '${COMMAND_PORT}:3000'
      - '9229:9229'  # 添加调试端口
    depends_on:
      - redis
      - mongo
    env_file:
      - .env

  worker:
    build:
      context: ./worker
    ports:
      - '${WORKER_PORT}:3000'
      - '9230:9229'  # 添加调试端口
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - shared-codes:/usr/src/app/dist/worker/codes

  worker-replica-1:
    build:
      context: ./worker
    ports:
      - '${WORKER_REPLICA_1_PORT}:3000'
      - '9231:9229'  # 添加调试端口
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - shared-codes:/usr/src/app/dist/worker/codes

  worker-replica-2:
    build:
      context: ./worker
    ports:
      - '${WORKER_REPLICA_2_PORT}:3000'
      - '9232:9229'  # 添加调试端口
    depends_on:
      - redis
      - mongo
    env_file:
      - .env
    volumes:
      - shared-codes:/usr/src/app/dist/worker/codes

volumes:
  mongo-data:
  shared-codes:
